name: Extract Air Quality JSON

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  extract:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: pip install pdfplumber pandas
      - name: Run extraction
        run: python parse.py
      - name: Upload JSON artifact
        uses: actions/upload-artifact@v3
        with:
          name: air-quality-data
          path: air_quality_data.json
