name: Extract Air Quality JSON

on:
  push:
    paths:
      - "Air Quality Data-VMC.pdf"
  workflow_dispatch:   # allow manual trigger

jobs:
  extract:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true  # needed to push changes
          fetch-depth: 0
          
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pdfplumber pandas
        
      - name: Run extraction script
        run: python parse.py

      - name: Commit JSON back to repo
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add air_quality_data.json
          git commit -m "chore: update air_quality_data.json from PDF [skip ci]" || echo "No changes to commit"
          git push
